version: '3.9'
services:
  api:
    build: ./backend
    container_name: video_api
    env_file:
      - ./backend/.env
    ports:
      - "8000:5000"
    depends_on:
      - redis
    volumes:
      - ./backend/storage:/app/storage
      - ./backend/uploads:/app/uploads
      - ./backend/app:/app/app:ro
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]
  worker:
    build: ./backend
    container_name: video_worker
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend/storage:/app/storage
      - ./backend/uploads:/app/uploads
    command: ["celery", "-A", "app.services.celery_app.celery_app", "worker", "--loglevel=info"]
  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: video_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
      - ./frontend/postcss.config.js:/app/postcss.config.js
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - api
  redis:
    image: redis:7-alpine
    container_name: video_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
