version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    env_file: ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API=http://localhost:8000
    depends_on:
      - backend
volumes:
  data:
